driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  # Port conflict issue
  # - name: debian-8
  # - name: debian-9
  # - name: centos-6
  - name: centos-7
  - name: fedora-latest
  - name: opensuse-leap

suites:
  - name: default
    run_list:
      - 'recipe[test::default]'
  - name: configure
    run_list:
      - 'recipe[test::configure]'
