---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - 'recipe[unbound::default]'
    attributes:
      dns:
        domain:
          id: int_example_com
          ns: [{ "int.example.com": "127.0.0.1" }]
          host: [{ "www.int.example.com": "10.1.1.200" }]