sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  # - INSTANCE=default-debian-8
  # - INSTANCE=default-debian-9
  # - INSTANCE=default-centos-6 port conflict
  - INSTANCE=default-centos-7
  - INSTANCE=default-fedora-27
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=default-opensuse-leap
  # - INSTANCE=configure-debian-8
  # - INSTANCE=configure-debian-9
  # - INSTANCE=configure-centos-6
  - INSTANCE=configure-centos-7
  - INSTANCE=configure-fedora-27
  - INSTANCE=configure-ubuntu-1604
  - INSTANCE=configure-ubuntu-1804
  - INSTANCE=configure-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
