---
jobs:
  final:
    docker:
      - image: bash:latest
    steps:
      - run:
          name: Finish cooking
          command: echo "Finished cooking"
lint_and_unit: &lint_and_unit
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
      - kitchen/yamllint:
          name: lint-yaml
      - kitchen/mdlint:
          name: lint-markdown
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/delivery:
          name: delivery
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1604
          suite: default-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-ubuntu-1804
          suite: default-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: default-opensuse-leap
          suite: default-opensuse-leap
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: configure-centos-7
          suite: configure-centos-7
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: configure-ubuntu-1604
          suite: configure-ubuntu-1604
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: configure-ubuntu-1804
          suite: configure-ubuntu-1804
          requires: *lint_and_unit
      - kitchen/dokken-single:
          name: configure-opensuse-leap
          suite: configure-opensuse-leap
          requires: *lint_and_unit
      - final:
          requires:
            - default-centos-7
            - default-ubuntu-1604
            - default-ubuntu-1804
            - default-opensuse-leap
            - configure-centos-7
            - configure-ubuntu-1604
            - configure-ubuntu-1804
            - configure-opensuse-leap
